# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipport < Formula
  desc "Cross-platform shared clipboard over TCP"
  homepage "https://github.com/tsyche/clipport"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.3/clipport_Darwin_x86_64.tar.gz"
      sha256 "7c917c90c31dcca033c951717efa1a3b0e9d310994b7ba921e7a798f06a6af85"

      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.3/clipport_Darwin_arm64.tar.gz"
      sha256 "df2d249160617fb813a26a00e8bbdfab3c5ae1c65f685e71213d2033900b2f47"

      define_method(:install) do
        bin.install "clipport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.3/clipport_Linux_x86_64.tar.gz"
      sha256 "a10c172e01c536c6ca87c2075f5dad02c195cfe4b37eadf622f99da5a47d3828"
      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.3/clipport_Linux_arm.tar.gz"
      sha256 "8eb2e08df74322bea1eb5a16173f2e9d6f4c662311630fe4c8402cb894150efa"
      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.3/clipport_Linux_arm64.tar.gz"
      sha256 "eea822d1451acc55084b83c5863f491ad34127f3ca23fe7770170c4057742dd6"
      define_method(:install) do
        bin.install "clipport"
      end
    end
  end

  test do
    system "#{bin}/clipport", "--help"
  end
end
