# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipport < Formula
  desc "Cross-platform shared clipboard over TCP"
  homepage "https://github.com/tsyche/clipport"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.7/clipport_Darwin_x86_64.tar.gz"
      sha256 "43eb7d85a8e187c3fe9c4719003c181af0678dbce5fc81672ae537afb0d29601"

      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.7/clipport_Darwin_arm64.tar.gz"
      sha256 "a30e4c39bf47ecd9d04c4623d33aa537543b54e176bfba22f244f97859edd54a"

      define_method(:install) do
        bin.install "clipport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.7/clipport_Linux_x86_64.tar.gz"
      sha256 "deb1bf7c450db9bfb97644fe7e99f63ed17d7cd4b0616395a7c0678ff3c7cce9"
      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.7/clipport_Linux_arm.tar.gz"
      sha256 "ece0d494bdf00e01c8a91e9fdad08cb6af142e56f167bd86ba15163fc8ff6131"
      define_method(:install) do
        bin.install "clipport"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsyche/clipport/releases/download/v0.1.7/clipport_Linux_arm64.tar.gz"
      sha256 "20bb6c1712184422b50054f0c6baa9259e566c71d93f76ea1c59f166f210bcbe"
      define_method(:install) do
        bin.install "clipport"
      end
    end
  end

  test do
    system "#{bin}/clipport", "--help"
  end
end
